/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum Explain {
    Notes = "notes",
    Fails = "fails",
    Full = "full",
    Debug = "debug",
}

/** @internal */
export const Explain$ = z.nativeEnum(Explain);
