/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum Explain {
    Notes = "notes",
    Fails = "fails",
    Full = "full",
    Debug = "debug",
}

/** @internal */
export namespace Explain$ {
    export const inboundSchema: z.ZodNativeEnum<typeof Explain> = z.nativeEnum(Explain);
    export const outboundSchema: z.ZodNativeEnum<typeof Explain> = inboundSchema;
}
