/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum GzipContentEncoding {
    Gzip = "gzip",
}

/** @internal */
export namespace GzipContentEncoding$ {
    export const inboundSchema = z.nativeEnum(GzipContentEncoding);
    export const outboundSchema = inboundSchema;
}
