/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum GzipContentEncoding {
    Gzip = "gzip",
}

/** @internal */
export const GzipContentEncoding$: z.ZodNativeEnum<typeof GzipContentEncoding> =
    z.nativeEnum(GzipContentEncoding);
