/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum GzipContentEncoding {
    Gzip = "gzip",
}

/** @internal */
export namespace GzipContentEncoding$ {
    export const inboundSchema: z.ZodNativeEnum<typeof GzipContentEncoding> =
        z.nativeEnum(GzipContentEncoding);
    export const outboundSchema: z.ZodNativeEnum<typeof GzipContentEncoding> = inboundSchema;
}
