/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum GzipAcceptEncoding {
    Gzip = "gzip",
}

/** @internal */
export namespace GzipAcceptEncoding$ {
    export const inboundSchema: z.ZodNativeEnum<typeof GzipAcceptEncoding> =
        z.nativeEnum(GzipAcceptEncoding);
    export const outboundSchema: z.ZodNativeEnum<typeof GzipAcceptEncoding> = inboundSchema;
}
