/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type HealthyServer = {};

/** @internal */
export namespace HealthyServer$ {
    export const inboundSchema: z.ZodType<HealthyServer, z.ZodTypeDef, unknown> = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, HealthyServer> = z.object({});
}
