/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Arbitrary JSON used within your policies by accessing `input`
 */
export type Input = boolean | string | number | Array<any> | { [k: string]: any };

/** @internal */
export namespace Input$ {
    export const inboundSchema: z.ZodType<Input, z.ZodTypeDef, unknown> = z.union([
        z.boolean(),
        z.string(),
        z.number(),
        z.array(z.any()),
        z.record(z.any()),
    ]);

    export type Outbound = boolean | string | number | Array<any> | { [k: string]: any };
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Input> = z.union([
        z.boolean(),
        z.string(),
        z.number(),
        z.array(z.any()),
        z.record(z.any()),
    ]);
}
