/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Arbitrary JSON used within your policies by accessing `input`
 */
export type Input = Record<string, any> | boolean | string | Array<any> | number;

/** @internal */
export namespace Input$ {
    export type Inbound = Record<string, any> | boolean | string | Array<any> | number;

    export type Outbound = Record<string, any> | boolean | string | Array<any> | number;
    export const inboundSchema: z.ZodType<Input, z.ZodTypeDef, Inbound> = z.union([
        z.record(z.any()),
        z.boolean(),
        z.string(),
        z.array(z.any()),
        z.number(),
    ]);
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Input> = z.union([
        z.record(z.any()),
        z.boolean(),
        z.string(),
        z.array(z.any()),
        z.number(),
    ]);
}
