/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Location = {
    file: string;
    row: number;
    col: number;
};

export type Errors = {
    code: string;
    message: string;
    location?: Location | undefined;
};

/**
 * Bad Request
 */
export type ClientErrorData = {
    code: string;
    message: string;
    errors?: Array<Errors> | undefined;
};

/**
 * Bad Request
 */
export class ClientError extends Error {
    code: string;
    errors?: Array<Errors> | undefined;

    /** The original data that was passed to this error instance. */
    data$: ClientErrorData;

    constructor(err: ClientErrorData) {
        super("");
        this.data$ = err;

        this.code = err.code;
        if (err.errors != null) {
            this.errors = err.errors;
        }

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "ClientError";
    }
}

/** @internal */
export namespace Location$ {
    export const inboundSchema: z.ZodType<Location, z.ZodTypeDef, unknown> = z.object({
        file: z.string(),
        row: z.number().int(),
        col: z.number().int(),
    });

    export type Outbound = {
        file: string;
        row: number;
        col: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Location> = z.object({
        file: z.string(),
        row: z.number().int(),
        col: z.number().int(),
    });
}

/** @internal */
export namespace Errors$ {
    export const inboundSchema: z.ZodType<Errors, z.ZodTypeDef, unknown> = z.object({
        code: z.string(),
        message: z.string(),
        location: z.lazy(() => Location$.inboundSchema).optional(),
    });

    export type Outbound = {
        code: string;
        message: string;
        location?: Location$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Errors> = z.object({
        code: z.string(),
        message: z.string(),
        location: z.lazy(() => Location$.outboundSchema).optional(),
    });
}

/** @internal */
export namespace ClientError$ {
    export const inboundSchema: z.ZodType<ClientError, z.ZodTypeDef, unknown> = z
        .object({
            code: z.string(),
            message: z.string(),
            errors: z.array(z.lazy(() => Errors$.inboundSchema)).optional(),
        })
        .transform((v) => {
            return new ClientError(v);
        });

    export type Outbound = {
        code: string;
        message: string;
        errors?: Array<Errors$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ClientError> = z
        .instanceof(ClientError)
        .transform((v) => v.data$)
        .pipe(
            z.object({
                code: z.string(),
                message: z.string(),
                errors: z.array(z.lazy(() => Errors$.outboundSchema)).optional(),
            })
        );
}
