/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnhealthyServerData = {
    code?: string | undefined;
};

export class UnhealthyServer extends Error {
    code?: string | undefined;

    /** The original data that was passed to this error instance. */
    data$: UnhealthyServerData;

    constructor(err: UnhealthyServerData) {
        super("");
        this.data$ = err;

        if (err.code != null) {
            this.code = err.code;
        }

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "UnhealthyServer";
    }
}

/** @internal */
export namespace UnhealthyServer$ {
    export const inboundSchema: z.ZodType<UnhealthyServer, z.ZodTypeDef, unknown> = z
        .object({
            code: z.string().optional(),
        })
        .transform((v) => {
            return new UnhealthyServer(v);
        });

    export type Outbound = {
        code?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnhealthyServer> = z
        .instanceof(UnhealthyServer)
        .transform((v) => v.data$)
        .pipe(
            z.object({
                code: z.string().optional(),
            })
        );
}
