/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ExecutePolicyRequest = {
    /**
     * The path separator is used to access values inside object and array documents. If the path indexes into an array, the server will attempt to convert the array index to an integer. If the path element cannot be converted to an integer, the server will respond with 404.
     */
    path?: string | undefined;
    /**
     * Indicates the server should respond with a gzip encoded body. The server will send the compressed response only if its length is above `server.encoding.gzip.min_length` value. See the configuration section
     */
    acceptEncoding?: components.GzipAcceptEncoding | undefined;
    /**
     * If parameter is `true`, response will formatted for humans.
     */
    pretty?: boolean | undefined;
    /**
     * If parameter is true, response will include build/version info in addition to the result.
     */
    provenance?: boolean | undefined;
    /**
     * Return query explanation in addition to result.
     */
    explain?: components.Explain | undefined;
    /**
     * Return query performance metrics in addition to result.
     */
    metrics?: boolean | undefined;
    /**
     * Instrument query evaluation and return a superset of performance metrics in addition to result.
     */
    instrument?: boolean | undefined;
    /**
     * Treat built-in function call errors as fatal and return an error immediately.
     */
    strictBuiltinErrors?: boolean | undefined;
};

export type ExecutePolicyResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Success.
     *
     * @remarks
     * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
     *
     */
    successfulPolicyResponse?: components.SuccessfulPolicyResponse | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export namespace ExecutePolicyRequest$ {
    export const inboundSchema: z.ZodType<ExecutePolicyRequest, z.ZodTypeDef, unknown> = z
        .object({
            path: z.string().default(""),
            "Accept-Encoding": components.GzipAcceptEncoding$.inboundSchema.optional(),
            pretty: z.boolean().optional(),
            provenance: z.boolean().optional(),
            explain: components.Explain$.inboundSchema.optional(),
            metrics: z.boolean().optional(),
            instrument: z.boolean().optional(),
            "strict-builtin-errors": z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "Accept-Encoding": "acceptEncoding",
                "strict-builtin-errors": "strictBuiltinErrors",
            });
        });

    export type Outbound = {
        path: string;
        "Accept-Encoding"?: string | undefined;
        pretty?: boolean | undefined;
        provenance?: boolean | undefined;
        explain?: string | undefined;
        metrics?: boolean | undefined;
        instrument?: boolean | undefined;
        "strict-builtin-errors"?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ExecutePolicyRequest> = z
        .object({
            path: z.string().default(""),
            acceptEncoding: components.GzipAcceptEncoding$.outboundSchema.optional(),
            pretty: z.boolean().optional(),
            provenance: z.boolean().optional(),
            explain: components.Explain$.outboundSchema.optional(),
            metrics: z.boolean().optional(),
            instrument: z.boolean().optional(),
            strictBuiltinErrors: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                acceptEncoding: "Accept-Encoding",
                strictBuiltinErrors: "strict-builtin-errors",
            });
        });
}

/** @internal */
export namespace ExecutePolicyResponse$ {
    export const inboundSchema: z.ZodType<ExecutePolicyResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            SuccessfulPolicyResponse: components.SuccessfulPolicyResponse$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                SuccessfulPolicyResponse: "successfulPolicyResponse",
                Headers: "headers",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        SuccessfulPolicyResponse?: components.SuccessfulPolicyResponse$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ExecutePolicyResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            successfulPolicyResponse:
                components.SuccessfulPolicyResponse$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                successfulPolicyResponse: "SuccessfulPolicyResponse",
                headers: "Headers",
            });
        });
}
