/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum GzipContentEncoding {
    Gzip = "gzip",
}

/** @internal */
export const GzipContentEncoding$ = z.nativeEnum(GzipContentEncoding);
