/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum GzipAcceptEncoding {
    Gzip = "gzip",
}

/** @internal */
export const GzipAcceptEncoding$ = z.nativeEnum(GzipAcceptEncoding);
