/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type HealthyServer = {};

/** @internal */
export namespace HealthyServer$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<HealthyServer, z.ZodTypeDef, Inbound> = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, HealthyServer> = z.object({});
}
