name: Test

on:
  workflow_dispatch: {}
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Compile and Test
        working-directory: ./
        run: |
          npm ci
          npx eslint --max-warnings=0 src README.md
          npx prettier . --check
          npx typedoc
          node --require ts-node/register --test tests/**/*.ts
