name: Test

on:
  workflow_dispatch: {}
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Compile, Lint
        run: |
          npm ci
          npx eslint --config=.eslintrc.styra.cjs --max-warnings=0 src README.md
          npx prettier . --check
          npx typedoc
      - name: Test
        run: node --import tsx --test tests/**/*.ts
        env:
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }}
